
### Use Postman to test the endpoints ###

## -------Auth------##

# register
### Inistructor ###
POST http://localhost:3000/api/v1/auth/register Content-Type: application/json
    {
        "name":"test",
        "email":"eba00@gmail.com",
        "password":"0992ixnc",
        "role":"Instructor"
    }


### Student ###
POST http://localhost:3000/api/v1/auth/register Content-Type: application/json
    {
        "name":"test",
        "email":"eba00@gmail.com",
        "password":"0992ixnc",
        "role":"Student"
    }


# Login
### Inistructor ###
POST http://localhost:3000/api/v1/auth/login Content-Type: application/json
    {
        "email":"eba00@gmail.com",
        "password":"0992ixnc",
        "role":"Instructor"
    }


### Student ###
POST http://localhost:3000/api/v1/auth/login Content-Type: application/json
    {
        "email":"eba00@gmail.com",
        "password":"0992ixnc",
        "role":"Student"
    }



## --------Courses-----##

### Get all courses ###
GET http://localhost:3000/api/v1/courses/ Content-Type: application/json
    authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwibmFtZSI6InRlc3QiLCJpYXQiOjE3MDU2NTczODEsImV4cCI6MTcwODI0OTM4MX0.NL5qClzKvPKyiCeN_otTMikQiBfmC_SL_YXiD8B-NxQ

### Get single course ###
#use the id of the course
GET http://localhost:3000/api/v1/courses/2 Content-Type: application/json
    authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwibmFtZSI6InRlc3QiLCJpYXQiOjE3MDU2NTczODEsImV4cCI6MTcwODI0OTM4MX0.NL5qClzKvPKyiCeN_otTMikQiBfmC_SL_YXiD8B-NxQ
